my_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: weather_postgres_db
      user: db_user
      password: db_password
      port: 5432
      dbname: db
      schema: weather
      threads: 1