services:
  db: 
    container_name: weather_postgres_db
    image: postgres:13.22
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
